### ISSUE TITLE
gto promote: not listed by gto -h

### ISSUE THREAD

**Issue by francesco086** [iterative/gto#253]
After upgrading to gto 0.2.2 when I run `gto -h`, the command `promote` is not listed.

However the command seems to be working.

**Comment by francesco086** [comment]
Actually the change happened from version 0.1.14 to 0.2.0.

**Comment by aguschin** [comment]
From the https://semver.org/#spec-item-4:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Yet, I guess I could upgrade minor each time, indicating these breaking changes. Then it should have been not `0.2.2`, but `0.3.0` already.

Eventually, the goal is to remove `promote`, cause we use `assign` in Studio and it's considered to be a better name for the action, that's why it's hidden.

**Comment by francesco086** [comment]
Ok, that's new to me, thanks for pointing it out! 
I always considered the `0.y.z` as any other version. 
Actually I never really understood why people are afraid of increasing these numbers, they don't cost money :D

Anyway, the issue is clearly resolved
