### ISSUE TITLE
--force flag for deprecate is not respected

### ISSUE THREAD

**Issue by jellebouwman** [iterative/gto#274]
### Scenario

After deprecating an artifact (`churn` in this example)

```
$ gto deprecate churn
```

The `churn@deprecated` tag is created.

When resurrecting the artifact by registering new versions / assigning stages (and the artifact showing up in after running `gto show`), subsequent deprecations are not allowed:

```
$ gto deprecate churn
❌ tag 'churn@deprecated' already exists
```

Using the `--force` flag makes no difference:

```
$ gto deprecate churn --force
❌ tag 'churn@deprecated' already exists
```

### Expected behaviour

I think `--force` should allow you to deprecate an artifact multiple times. This could be because
- I genuinely want to be able to deprecate and resurrect artifacts at will
- I want to re-deprecate an artifact that I accidentally resurrected.

**Comment by aguschin** [comment]
@jellebouwman, this is because the Git tag already exists. So you try to create the tag with the same name, which doesn't work in Git.

```shell
$ gto deprecate churn --force --simple false
Created git tag 'churn@deprecated#2' that deprecates artifact
To push the changes upstream, run:
    git push churn@deprecated#2
```

There are couple ways to fix this:
1. Make error message more meaningful (ask to add `--simple false`)
2. Since by default it is `--simple auto`, make use of the `auto` and imply `--simple false`.

**Comment by aguschin** [comment]
I like the last approach, but it may users life harder if he wants for GTO to be predictable. But, in this case, he can always supply `--simple false` or `--simple true` instead of using default.

This `--simple auto` exists in the first place to support differently treating registrations and assignments. For registrations, you usually don't need counter in the end (`nn@v0.0.1` instead of `nn@v0.0.1#2`, cause registration Git tags are rarely exist), but you need them for assignments (`nn#prod#4` instead of `nn#prod`, cause this will often happen).

WDYT?

**Comment by jellebouwman** [comment]
Hey @aguschin thanks for getting back to me!

> @jellebouwman, this is because the Git tag already exists. So you try to create the tag with the same name, which doesn't work in Git.

I missed this fundamental part - thank you 🙏 

> I like the last approach, but it may users life harder if he wants for GTO to be predictable. But, in this case, he can always supply --simple false or --simple true instead of using default.

Thank you for this approach - I think I will use it in Studio's scenario. At this point we can not detect whether or not the user's repository is entirely using `simple`, not `simple` or a hybrid. For `register` and `assign` we now default to `simple=False`, I think I'll do the same thing for `deprecate` in this scenario.

To the original issue: when using `--simple false` in the CLI, the `--force` flag is respected. So closing this issue.

Thanks again @aguschin! ❤️

**Comment by aguschin** [comment]
Thanks @jellebouwman.
I think I will still implement the 2nd approach I suggested, so reopening the issue.
