### ISSUE TITLE
gto describe fails on windows 10 python 3.11

### ISSUE THREAD

**Issue by fortminors** [iterative/gto#347]
Hello! I am using DVC with GTO to build model registry.

I am currently working on Windows 10 machine (on linux, ubuntu it works well)

I am trying to download the model through `dvc get` but I fail before that using `gto describe`.
It says that maybe the cause is that I am using python 3.9, but I am actually on python 3.11

Here is what I am doing: Please help! @aguschin 

$ `gto doctor`

```
🪴  GTO Version: 0.2.7
---------------------------------
INDEX='artifacts.yaml'
TYPES=None
STAGES=None
LOG_LEVEL='INFO'
DEBUG=False
ENRICHMENTS=[]
AUTOLOAD_ENRICHMENTS=True
CONFIG_FILE_NAME='.gto'
EMOJIS=True
---------------------------------
❌ No Git repo found in '.'

```

$ `gto --traceback describe --repo https://<user>:<token>@gitlab.com/<repo_url>.git <model_name>@latest`

Output:

https://pastebin.com/T60M2quZ

**Comment by aguschin** [comment]
Hi @fortminors! Yep, it looks like some windows problems.

I won't be fixing this, since we're dropping `gto describe` #346 soon, and we're going to introduce simply `dvc get $REPO :<model_name>`, but that will take a few weeks.

For now the workaround for you would be running `git clone` and working with the cloned repo.

**Comment by aguschin** [comment]
The other workaround maybe could be changing reading/writing rights on `C:\\Users\\<user>\\AppData\\Local\\Temp\\`, but I don't have a windows machine myself and can't check how to make it work. 

I found this issue explaining the same problem and suggesting the same solution, maybe it's a solution indeed https://stackoverflow.com/questions/61409100/permission-error-cloning-git-repository-in-temporary-folder

But if we're to apply SO suggestion exactly, we need to make an update to GTO codebase - and I don't think we need that  generally due to soon `describe` deprecation. If you want to contribute a fix, I would be happy to merge/release it though.

**Comment by fortminors** [comment]
Got it, thank you for your suggestions! I will try it out
